allowBuilds:
  '@parcel/watcher': set this to true or false
  core-js: set this to true or false
  esbuild: set this to true or false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.4
  vite-plus: 0.2.4
minimumReleaseAgeExclude:
  - '@xmldom/xmldom@0.9.11'
overrides:
  vite: 'catalog:'
  '@xmldom/xmldom': 0.9.11
  glob: ^13.0.6
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
